routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//pagina de visitas
Route::get('/','FrontController@index');
Route::get('/servicios','FrontController@service');
Route::get('/galeria','FrontController@galery');
Route::get('/preguntas','FrontController@question');
Route::get('/contacto','FrontController@contact');
Auth::routes(['verify' => true]);
//inventario
Route::resource('garments', 'GarmentController');
Route::resource('discounts', 'DiscountController'); //
Route::resource('suits', 'SuitController');
Route::resource('motleys', 'MotleyController');
Route::resource('packages', 'PackageController');
Route::resource('characters', 'CharacterController');
Route::resource('props', 'PropController');//
//administracion
Route::get('/home', 'HomeController@index')->middleware('verified');
Route::get('/01010100_01100101_00100000_01100001_01101101_01101111_00100000_01001101_01100001_01110010_01101001_01110011_01101111_01101100','HomeController@secret');
Route::resource('animators', 'AnimatorController');//
Route::resource('workers', 'WorkerController');
Route::resource('posts', 'PostController');
//administrar categorias
Route::resource('categoryCharacters', 'CategoryCharacterController');
Route::resource('categoryProps', 'CategoryPropController');
Route::resource('categoryGarments', 'CategoryGarmentController');
//rutas de prueba
//Route::get('/contrato', 'PruebasController@contract');
Route::resource('contracts', 'ContractController');
Route::resource('locations', 'LocationController');
Route::resource('users', 'UserController');
Route::resource('roles', 'RoleController');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::get('cotizacion','WizardController@getWizard');
/////////////////////////////PRUEBAS //////////////////////////////////////////////////////////
Route::name('imprimir')->get('/imprimir-pdf','WizardController@downPdf');
Route::get('pruebas','ContractController@getCalculations');



Route::resource('events', 'EventController');

app/Models/CategoryCharacter.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class CategoryCharacter
 * @package App\Models
 * @version March 28, 2020, 5:48 am UTC
 *
 * @property string name
 * @property string description
 */
class CategoryCharacter extends Model
{
    use SoftDeletes;

    public $table = 'category_characters';
    

    protected $dates = ['deleted_at'];



    public $fillable = [
        'name',
        'description'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'description' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'name' => 'required',
        'description' => 'required'
    ];
    public function characters(){
        return $this->hasMany('App\Models\Character');
    }
    
}

app/Http/Controllers/CategoryCharacterController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateCategoryCharacterRequest;
use App\Http\Requests\UpdateCategoryCharacterRequest;
use App\Repositories\CategoryCharacterRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class CategoryCharacterController extends AppBaseController
{
    /** @var  CategoryCharacterRepository */
    private $categoryCharacterRepository;

    public function __construct(CategoryCharacterRepository $categoryCharacterRepo)
    {
        $this->categoryCharacterRepository = $categoryCharacterRepo;
    }

    /**
     * Display a listing of the CategoryCharacter.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $categoryCharacters = $this->categoryCharacterRepository->all();

        return view('category_characters.index')
            ->with('categoryCharacters', $categoryCharacters);
    }

    /**
     * Show the form for creating a new CategoryCharacter.
     *
     * @return Response
     */
    public function create()
    {
        return view('category_characters.create');
    }

    /**
     * Store a newly created CategoryCharacter in storage.
     *
     * @param CreateCategoryCharacterRequest $request
     *
     * @return Response
     */
    public function store(CreateCategoryCharacterRequest $request)
    {
        $input = $request->all();

        $categoryCharacter = $this->categoryCharacterRepository->create($input);

        Flash::success('La Categoria se guardo con Exito.');

        return redirect(route('categoryCharacters.index'));
    }

    /**
     * Display the specified CategoryCharacter.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $categoryCharacter = $this->categoryCharacterRepository->find($id);

        if (empty($categoryCharacter)) {
            Flash::error('Categoria no encontrada');

            return redirect(route('categoryCharacters.index'));
        }

        return view('category_characters.show')->with('categoryCharacter', $categoryCharacter);
    }

    /**
     * Show the form for editing the specified CategoryCharacter.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $categoryCharacter = $this->categoryCharacterRepository->find($id);

        if (empty($categoryCharacter)) {
            Flash::error('Categoria no encontrada');

            return redirect(route('categoryCharacters.index'));
        }

        return view('category_characters.edit')->with('categoryCharacter', $categoryCharacter);
    }

    /**
     * Update the specified CategoryCharacter in storage.
     *
     * @param int $id
     * @param UpdateCategoryCharacterRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateCategoryCharacterRequest $request)
    {
        $categoryCharacter = $this->categoryCharacterRepository->find($id);

        if (empty($categoryCharacter)) {
            Flash::error('Categoria no encontrada');

            return redirect(route('categoryCharacters.index'));
        }

        $categoryCharacter = $this->categoryCharacterRepository->update($request->all(), $id);

        Flash::success('La Categoria fue Actualizada con Exito.');

        return redirect(route('categoryCharacters.index'));
    }

    /**
     * Remove the specified CategoryCharacter from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $categoryCharacter = $this->categoryCharacterRepository->find($id);

        if (empty($categoryCharacter)) {
            Flash::error('Categoria no encontrada');

            return redirect(route('categoryCharacters.index'));
        }

        $this->categoryCharacterRepository->delete($id);

        Flash::success('La Categoria fue Eliminada con Exito.');

        return redirect(route('categoryCharacters.index'));
    }
}

resources/views/category_characters/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Categoria de personajes
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">

                    {!! Form::open(['route' => 'categoryCharacters.store']) !!}


                        <div class="col-md-12">
                            <!-- jquery validation -->
                            <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Categoria <small>Nueva</small></h3>
                            </div>
                            <!-- /.card-header -->
                            <!-- form start -->
                            @include('category_characters.fields')
                            </div>
                            <!-- /.card -->
                        </div>

                    {!! Form::close() !!}

            </div>
        </div>
    </div>
@endsection

resources/views/category_characters/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
        Categoria de personajes
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">

                   {!! Form::model($categoryCharacter, ['route' => ['categoryCharacters.update', $categoryCharacter->id], 'method' => 'patch']) !!}

                   <div class="col-md-12">
                    <!-- jquery validation -->
                    <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Categoria <small>Editar</small></h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    @include('category_characters.fields')
                    </div>
                    <!-- /.card -->
                </div>

                   {!! Form::close() !!}

           </div>
       </div>
   </div>
@endsection

resources/views/category_characters/fields.blade.php
<!-- Name Field -->
<div class="row">
    <div class=" offset-md-2 form-group col-md-6">
        {!! Form::label('name', 'Nombre:') !!}
        {!! Form::text('name', null, ['class' => 'form-control']) !!}
    </div>

    <!-- Description Field -->
    <div class="offset-md-2 form-group col-md-6">
        {!! Form::label('description', 'Descripcion:') !!}
        {!! Form::textarea('description', null, ['class' => 'form-control']) !!}
    </div>

</div>

<div class="row">
	<div class="offset-md-3 col-md-2">
		<a href="{!! route('categoryCharacters.index') !!}" class="btn btn-block bg-gradient-danger btn-flat">
			<i class="fas fa-reply"></i>
			<p>Atras</p>
		</a>
	</div>
	<div class="col-md-2">
		<button class="btn btn-block bg-gradient-success btn-flat " type="submit">
			<i class="	fas fa-save"></i>
			<p>Guardar</p>
		</button>
    </div>
</div>

resources/views/category_characters/index.blade.php
@extends('layouts.app')

@section('content')
@if(\Auth::check() && \Auth::user()->can('Create'))

    <section class="content-header">
        <h1 class="pull-right">
           <a class="btn btn-block btn-primary btn-lg" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('categoryCharacters.create') }}">Añadir Nueva Categoria</a>
        </h1>
    </section>
@endif
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('category_characters.table')


            </div>
        </div>
        <div class="text-center">

        </div>
    </div>
@endsection

resources/views/category_characters/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
        Categoria de personajes
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">

                    <div class="col-md-12">
                        <!-- jquery validation -->
                        <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Categoria <small>Ver</small></h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        @include('category_characters.show_fields')
                        <div class="row">
                            <div class="offset-md-3 col-md-2">
                                <a href="{!! route('categoryCharacters.index') !!}" class="btn btn-block bg-gradient-danger btn-flat">
                                    <i class="fas fa-reply"></i>
                                    <p>Atras</p>
                                </a>
                            </div>
                        </div>
                        <!-- /.card -->
                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/category_characters/show_fields.blade.php
<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Nombre:') !!}
    <p>{{ $categoryCharacter->name }}</p>
</div>

<!-- Description Field -->
<div class="form-group">
    {!! Form::label('description', 'Descripcion:') !!}
    <p>{{ $categoryCharacter->description }}</p>
</div>

resources/views/category_characters/table.blade.php
<div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Categoria de Personajes</h3>

                <div class="card-tools">
                  <div class="input-group input-group-sm" style="width: 150px;">
                    <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                    <div class="input-group-append">
                      <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                    </div>
                  </div>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap">
                  <thead>
                    <tr>
                      <th>Nombre</th>
                      <th>Descripcion</th>
                      <th>Administrar</th>

                    </tr>
                  </thead>
                  <tbody>
                @foreach($categoryCharacters as $categoryCharacter)
                    <tr>
                      <td>{{ $categoryCharacter->name }}</td>
                      <td>{{ $categoryCharacter->description }}</td>
                      <td>{!! Form::open(['route' => ['categoryCharacters.destroy', $categoryCharacter->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        @if(\Auth::user()->can('Edit'))
                        <a href="{{ route('categoryCharacters.edit', [$categoryCharacter->id]) }}" class='btn btn-info btn-sm'><i class="fas fa-pencil-alt"></i> Editar</a>
                        @endif
                        @if(\Auth::user()->can('Delete'))
                        {!! Form::button('<i class="fas fa-trash"></i> Eliminar', ['type' => 'submit', 'class' => 'btn btn-danger btn-sm', 'onclick' => "return confirm('Esta seguro de eliminar la categoria: $categoryCharacter->name ?')"]) !!}
                        @endif
                    </div>
                    {!! Form::close() !!}</td>
                    </tr>
                @endforeach
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>